"""Add session_id to Reservation

Revision ID: 31c376b3eb81
Revises: 
Create Date: 2024-11-21 22:43:04.721750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c376b3eb81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('user_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('user_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('max_users',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('choice_timeout',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('queue_timeout',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('max_events',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('max_events',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('queue_timeout',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('choice_timeout',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('max_users',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('user_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('user_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
